# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, debian-13]
        # Support debian-latest later by self-hosting a runner
        python-version: ["3.12", "3.13"]
        exclude:
          - os: debian-13
            python-version: "3.14"  # Not yet available on Debian-13

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.os != 'debian-13'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }} on Debian-12
      if: matrix.os == 'debian-13'
      # Consider python-*-full later if needed
      run: |
        sudo apt install -y python${{ matrix.python-version }}-minimal
    - name: Upgrade Pip and Install flake8 dependency
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
      # The following line only works on unix systems:
      # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check for requirements.txt
      id: check_file
      uses: andstor/file-existence-action@v1
      with:
        files: "requirements.txt"
    - name: Install dependencies if requirements.txt exists
      if: steps.check_file.outputs.filesExist == 'true'
      run: pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install src files as package 
      run: |
        pip install -e . --config-settings editable_mode=strict
    - name: Test with unittest
      run: |
        python -m unittest discover -s ./tests -p '*_tests.py'
